### PR TITLE
Add Telepresence and local setup instructions

### LINKED ISSUE #7: Automate daiteap development environment
Current setup:
- automated local platform deployment with docker-compose

Pros:
- fully automated local setup
- well documented

Cons:
- unrealistic deployment (production uses Kubernetes cluster instead of docker-compose)
- hard development/debugging - do not describe how to run and configure services locally (daiteap-ui)

Daiteap-dev-setup

Tasks:
- [x] deploy local environment using devcontainer and KIND cluster
- [x] install and configure ArgoCD
- [x] create repos in ArgoCD
- [x] create applications in ArgoCD
- [x] Modify HELM charts to always use Daiteap public images
- [x] Modify ArgoCD repos to point to public daiteap repos in github.com
- [x] Remove Credentials steps from README-devcontainer-auto.md, because they are not needed. Everything for the deployment is public.
- [x] Update `master` branchs on public github repositories for daiteap to be up-to-date with versions in gitlab.cst-bg.net
- [x] Use Github Actions to automatically build and publish docker images to github Container Registry. Update all references in the deployment to point to the new images in github.com
- [x] Use public helm charts for dependent components keycloak, mysql, redis, rabitmqbroker, vault. Fix the versions of public components.
- [x] Copy nfs_server and mysql charts to github platform repo.
- [x] Clear all "cst" from repo files.
- [x] sync applications in ArgoCD
- [x] configure and init daiteap platform
- [x] document how to debug individual modules with telepresence
- [x] add instructions how to start front-end and back-end locally

### PR DESCRIPTION
**Pull request by vikig07**

### CODE REVIEW

**Comment by darashevcstbg** [comment]
- Keycloak setup steps can be automated.

- After restarting VS code, the vault is locked, and port forward is missing. There is no documentation how to fix it.

- I get an error running init-telepresence.sh script
    <details>
    <summary>Show more</summary>
      
    ```bash
    ./scripts/init-telepresence.sh
    --- Install Telepresence + SSHFS ---
    fs.inotify.max_user_instances = 1000000
    fs.inotify.max_user_watches = 1000000
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                      Dload  Upload   Total   Spent    Left  Speed
    100   106  100   106    0     0    132      0 --:--:-- --:--:-- --:--:--   132
    100 96.3M  100 96.3M    0     0  4905k      0  0:00:20  0:00:20 --:--:-- 7706k
    Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
    Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                            
    Get:3 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy InRelease [3,611 B]
    Get:4 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [456 kB]
    Get:5 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy/main all Packages [904 B]
    Get:6 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy/main amd64 Packages [65.9 kB]     
    Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [575 kB]                              
    Get:8 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.3 kB]         
    Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [928 kB]                                     
    Get:10 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                    
    Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
    Get:12 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
    Get:13 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
    Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
    Get:15 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
    Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.2 kB]
    Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [857 kB]
    Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [457 kB]
    Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,176 kB]
    Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [27.0 kB]
    Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [49.4 kB]
    Fetched 25.0 MB in 4s (6,458 kB/s)                          
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    All packages are up to date.
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    The following additional packages will be installed:
      fuse3 libfuse3-3 libglib2.0-0 libglib2.0-data shared-mime-info xdg-user-dirs
    The following NEW packages will be installed:
      fuse3 libfuse3-3 libglib2.0-0 libglib2.0-data shared-mime-info sshfs xdg-user-dirs
    0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
    Need to get 2,126 kB of archives.
    After this operation, 8,165 kB of additional disk space will be used.
    Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-0 amd64 2.72.4-0ubuntu2 [1,462 kB]
    Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-data all 2.72.4-0ubuntu2 [4,968 B]
    Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 shared-mime-info amd64 2.1-2 [454 kB]
    Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 xdg-user-dirs amd64 0.17-2ubuntu4 [53.9 kB]
    Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfuse3-3 amd64 3.10.5-1build1 [81.2 kB]
    Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 fuse3 amd64 3.10.5-1build1 [24.7 kB]
    Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 sshfs amd64 3.7.1+repack-2 [45.1 kB]
    Fetched 2,126 kB in 1s (1,803 kB/s)
    Selecting previously unselected package libglib2.0-0:amd64.
    (Reading database ... 22432 files and directories currently installed.)
    Preparing to unpack .../0-libglib2.0-0_2.72.4-0ubuntu2_amd64.deb ...
    Unpacking libglib2.0-0:amd64 (2.72.4-0ubuntu2) ...
    Selecting previously unselected package libglib2.0-data.
    Preparing to unpack .../1-libglib2.0-data_2.72.4-0ubuntu2_all.deb ...
    Unpacking libglib2.0-data (2.72.4-0ubuntu2) ...
    Selecting previously unselected package shared-mime-info.
    Preparing to unpack .../2-shared-mime-info_2.1-2_amd64.deb ...
    Unpacking shared-mime-info (2.1-2) ...
    Selecting previously unselected package xdg-user-dirs.
    Preparing to unpack .../3-xdg-user-dirs_0.17-2ubuntu4_amd64.deb ...
    Unpacking xdg-user-dirs (0.17-2ubuntu4) ...
    Selecting previously unselected package libfuse3-3:amd64.
    Preparing to unpack .../4-libfuse3-3_3.10.5-1build1_amd64.deb ...
    Unpacking libfuse3-3:amd64 (3.10.5-1build1) ...
    Selecting previously unselected package fuse3.
    Preparing to unpack .../5-fuse3_3.10.5-1build1_amd64.deb ...
    Unpacking fuse3 (3.10.5-1build1) ...
    Selecting previously unselected package sshfs.
    Preparing to unpack .../6-sshfs_3.7.1+repack-2_amd64.deb ...
    Unpacking sshfs (3.7.1+repack-2) ...
    Setting up xdg-user-dirs (0.17-2ubuntu4) ...
    Setting up libglib2.0-0:amd64 (2.72.4-0ubuntu2) ...
    No schema files found: doing nothing.
    Setting up libglib2.0-data (2.72.4-0ubuntu2) ...
    Setting up shared-mime-info (2.1-2) ...
    Setting up libfuse3-3:amd64 (3.10.5-1build1) ...
    Setting up fuse3 (3.10.5-1build1) ...
    Setting up sshfs (3.7.1+repack-2) ...
    Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
    Processing triggers for man-db (2.10.2-1) ...
    --- Install Telepresence In Cluster ---
    Launching Telepresence User Daemon
    
    Traffic Manager installed successfully
    ---- Waiting For Telepresence Pod ----
    pod/traffic-manager-5db77bff74-lxwhz condition met
    --- Connect To Cluster ---
    Launching Telepresence Root Daemon
    Connected to context kind-kind (https://127.0.0.1:44963)
    HTTP/2 403 
    audit-id: 587bed81-e214-4645-9f3b-b86cc98b003a
    cache-control: no-cache, private
    content-type: application/json
    x-content-type-options: nosniff
    x-kubernetes-pf-flowschema-uid: 61135344-b4e8-4a72-ae12-e9e9f93a2d4d
    x-kubernetes-pf-prioritylevel-uid: 61050f7e-2075-403c-8526-aa0736c88991
    content-length: 217
    date: Mon, 12 Jun 2023 10:41:31 GMT
    
    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
      "reason": "Forbidden",
      "details": {},
      "code": 403
    }
    ```
    </details>

**Comment by akafazov** [comment]
When I boot up the devcontainer, there is often the old `kind` cluster still there. It causes issues when trying to delete it. 

We should add commands to tear down old resources.

**Comment by vikig07** [comment]
There is a script for deleting the cluster `./scripts/delete-cluster.sh`, it's mentioned at the end of the README.

**Comment by darashevcstbg** [comment]
Missing information how to access Keycloak

**Comment by akafazov** [comment]
> There is a script for deleting the cluster `./scripts/delete-cluster.sh`, it's mentioned at the end of the README.

I tried it but it doesn't work. There are some issues on my machine.

**Comment by akafazov** [comment]
There are no instructions how to login to keyclaok and enable the user.

**Comment by vikig07** [comment]
> > There is a script for deleting the cluster `./scripts/delete-cluster.sh`, it's mentioned at the end of the README.
> 
> I tried it but it doesn't work. There are some issues on my machine.

What are the issues?

**Comment by akafazov** [comment]
> > > There is a script for deleting the cluster `./scripts/delete-cluster.sh`, it's mentioned at the end of the README.
> > 
> > 
> > I tried it but it doesn't work. There are some issues on my machine.
> 
> What are the issues?

Not sure, but resolved them by restarting docker service. The rest works.

**Comment by darashevcstbg** [comment]
Works for me.

**Review by darashevcstbg — APPROVED** [review]

**Pull request merged**
